global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['34.228.88.66:8083']

remote_write:
  - url: https://prometheus-prod-52-prod-ap-southeast-2.grafana.net/api/prom/push
    basic_auth:
      username: "2460403"
      password: "${GRAFANA_API_KEY}"