name: Deploy Spring Boot with Gradle

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Render prometheus.yml from template
        run: |
          sed "s|\${GRAFANA_API_KEY}|${{ secrets.GRAFANA_API_KEY }}|g" monitoring/prometheus/prometheus.yml > prometheus.yml

      - name: Upload JAR and prometheus.yml to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ec2-user
          key: ${{ secrets.AWS_SSH_KEY }}
          source: "build/libs/*.jar,prometheus.yml"
          target: "/home/ec2-user/"

      - name: Restart app on EC2 using existing .env_rating
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ec2-user
          key: ${{ secrets.AWS_SSH_KEY }}
          timeout: 10m
          command_timeout: 10m
          script: |
            set -x
            nohup bash -c "source /home/ec2-user/.env_rating && java -jar /home/ec2-user/rating-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod --server.address=0.0.0.0" > /home/ec2-user/app.log 2>&1 &

            echo "App restarted using existing .env_rating"
