name: Deploy Spring Boot to AWS
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build  # Ganti ./mvnw package dengan ./gradlew build

      - name: Upload JAR to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_HOST }}  # Elastic IP
          username: ec2-user
          key: ${{ secrets.AWS_SSH_KEY }}  # Isi dengan private key (.pem)
          source: "build/libs/*.jar"       # Path JAR hasil Gradle
          target: "/home/ec2-user/"